# if you are looking for a working example
# refer to https://github.com/randy3k/UnitTesting-example/blob/master/.travis.yml

# use container based infrastructure
sudo: false

os:
    - linux
    - osx

env:
    global:
        - PACKAGE="UnitTesting"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"
        - SUBLIME_TEXT_VERSION="2" PCINSTALL=true
        - SUBLIME_TEXT_VERSION="3" PCINSTALL=true
        - SUBLIME_TEXT_VERSION="2" PACKAGE_RELOADER_TAG="master"
        - SUBLIME_TEXT_VERSION="3" PACKAGE_RELOADER_TAG="master"

matrix:
  allow_failures:
    - env:
        - SUBLIME_TEXT_VERSION="2" PACKAGE_RELOADER_TAG="master"
        - SUBLIME_TEXT_VERSION="3" PACKAGE_RELOADER_TAG="master"

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh sbin/travis.sh bootstrap
    - if [ "$PCINSTALL" == true ]; then sh sbin/travis.sh install_package_control; fi

script:
    - sh sbin/travis.sh run_tests --coverage

after_success:
    - if [ "$SUBLIME_TEXT_VERSION" == "3" ]; then
            pip install --user python-coveralls;
            coveralls;
      fi

notifications:
    email:
        on_success: change
        on_failure: change
