# if you are looking for a working example
# refer to https://github.com/randy3k/UnitTesting-example/blob/master/appveyor.yml

environment:
    global:
        # Your package name
        PACKAGE: "UnitTesting"
    matrix:
        - SUBLIME_TEXT_VERSION : "2"
        - SUBLIME_TEXT_VERSION : "3"
          PYTHON: "C:\\Python33"
        - SUBLIME_TEXT_VERSION : "2"
          PCINSTALL: true
        - SUBLIME_TEXT_VERSION : "3"
          PYTHON: "C:\\Python33"
          PCINSTALL: true

install:
    - ps: .\sbin\appveyor.ps1 "bootstrap" -verbose
    - ps: if (${env:PCINSTALL} -eq $true) { .\sbin\appveyor.ps1 "install_package_control" -verbose }

build: off

test_script:
    - ps: .\sbin\appveyor.ps1 "run_tests" -coverage -verbose

# it is not quiet working
# on_success:
#     - ps: |
#         if (${env:SUBLIME_TEXT_VERSION} -eq 3) {
#             $branch = git name-rev --name-only HEAD | out-string
#             invoke-expression "git checkout -q $branch" -erroraction silentlycontinue
#             pip install coveralls
#             invoke-expression "coveralls 2>&1" -erroraction silentlycontinue
#         }
